### ISSUE TITLE
not working in latest safari

### ISSUE THREAD

**Issue by rafaelkallis** [mnbucher/olat#1]
Working in latest chrome, but not in latest safari.

Might be possible that stylish is not compatible to safari anymore due to breaking changes.

macOS Sierra 10.12.4
Safari Version 10.1 (12603.1.30.0.34)

**Comment by mnbucher** [comment]
I'm on the same builds with

macOS Sierra 10.12.4
Safari Version 10.1 (12603.1.30.0.34)

and it works like a charm. On what Stylish version are you? I'm on 1.9.8

There are strange cases where the CSS doesn't seem to overwrite the default (1 of 100 times when I'm opening OLAT). But I'm not really sure if it's a problem of stylish or not.

**Comment by rafaelkallis** [comment]
Stylish is also on 1.9.8 on my side. Note that I've installed Stylish using the official safari extensions library.

**Comment by mnbucher** [comment]
Hi Rafael, I think I found out what could cause the trouble with the settings in Safari. Try adding the following under «Applies to»

URL: https://lms.uzh.ch/dmz/

Does it work now?

**Comment by rafaelkallis** [comment]
Unfortunately not. But it makes sense that it won't change anything since the **URL prefix** https://lms.uzh.ch already includes the **/dmz** route

I've also included a screenshot in case you see something I don't.

<img width="1014" alt="screen shot 2017-05-03 at 23 41 02" src="https://cloud.githubusercontent.com/assets/9661903/25682855/04570d24-305a-11e7-9cad-21107fef5975.png">

**Comment by mnbucher** [comment]
Hmm strange... I added the last URL because OLAT is making some internal routing which stylish doesn't seem to apply always, which seems to be solved with the /dmz/ path. Under which URL are you trying to access the OLAT page?

**Comment by rafaelkallis** [comment]
Tried both **olat.uzh.ch** and **lms.uzh.ch** which redirect me to **https://lms.uzh.ch/dmz**

**Comment by rafaelkallis** [comment]
Interesting update regarding the topic. It seems that after I restarted the OS, the css works as expected. Clearing caches was apparently not enough!

Thanks again for your work.

**Comment by mnbucher** [comment]
Glad to hear that! For any improvements just fork and make a pull request, I'm open for every kind of enhancement!
